name 'packer-templates'
maintainer 'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license 'all_rights'
description 'Resources run during packer builds'
long_description 'Resources run during packer builds'
version '0.1.0'

depends 'windows'
depends 'wsus-client'
